### ISSUE TITLE
forge-1.12.2-14.23.5.2859 server stop while online throws an exception

### ISSUE THREAD

**Issue by powerjungle** [Quetzi/Morpheus#101]
Happens when I stop the server using the command while my client is still in it.

Morpheus-1.12.2-3.5.106

```
> stop
[16:03:36] [Server thread/INFO] [minecraft/DedicatedServer]: Stopping the server
[16:03:36] [Server thread/INFO] [simplelogin]: Shutting down player login handler
[16:03:36] [Server thread/INFO] [simplelogin]: Saving all entries
[16:03:36] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:03:36] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[16:03:36] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[16:03:36] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'buildcraft-world'/overworld
[16:03:36] [Server thread/INFO] [FML]: Unloading dimension 0
[16:03:36] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:03:36] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
[16:03:36] [Server Shutdown Thread/INFO] [minecraft/NetHandlerPlayServer]: user lost connection: Server closed
[16:03:36] [Server Shutdown Thread/INFO] [minecraft/DedicatedServer]: user left the game
[16:03:36] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@2ff18d26:
java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:248) ~[DimensionManager.class:14.23.5.2859]
	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:832) ~[MinecraftServer.class:?]
	at net.quetzi.morpheus.helpers.MorpheusEventHandler.loggedOutEvent(MorpheusEventHandler.java:38) ~[MorpheusEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_MorpheusEventHandler_loggedOutEvent_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:388) [pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853) [pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453) [gw.class:?]
	at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:291) [pa$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_345]
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:287) [pa.class:?]
	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1084) [pl.class:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:431) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579) [MinecraftServer$4.class:?]
```

**Comment by powerjungle** [comment]
Closing, because it's old.
